name: Build and Test
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      shell: bash
      run: |
        # apt dependencies
        sudo apt install ninja-build ccache
        sudo mkdir -p /usr/lib/ccache/bin

        # Download the most recent release of the riscv compilers for ubuntu 22.04.
        # We'll do this by querying the Github API for the most recent releases,
        # filter by artifacts that are named like we expect, and wget/extract them.
        TOOLCHAIN_URLS=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/riscv-collab/riscv-gnu-toolchain/releases | \
            jq -r '.[0][] | select(. | type == "array") |
              map(select(.name | match("glibc-ubuntu-22.04-gcc"))) |
              map(.browser_download_url)[]')

        for url in $TOOLCHAIN_URLS ; do wget -q "$url" ; done
        for f in *.tar.gz ; do tar xf "$f" ; done
        sudo mv riscv /opt

        # Link RISC-V compilers to ccache
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/riscv32-unknown-linux-gnu-gcc
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/riscv32-unknown-linux-gnu-g++
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/riscv32-unknown-linux-gnu-c++
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/riscv64-unknown-linux-gnu-gcc
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/riscv64-unknown-linux-gnu-g++
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/riscv64-unknown-linux-gnu-c++

        # Link native compilers to ccache
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/gcc
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/g++
        sudo ln -s /usr/bin/ccache /usr/lib/ccache/bin/c++

    # Checkout the project
    - name: Checkout SMMTT
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    # Get various keys for various caches
    - name: Get cache keys
      id: cache-keys
      run: |
        # Grab some timestamps for compiler caches
        echo "CCKEY=$(date -u +'%Y-%m-%d-%H')-$(uuidgen)" >> "$GITHUB_OUTPUT"
        echo "YMDH=$(date -u +'%Y-%m-%d-%H')" >> "$GITHUB_OUTPUT"
        echo "YMD=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
        echo "YM=$(date -u +'%Y-%m')" >> "$GITHUB_OUTPUT"
        echo "Y=$(date -u +'%Y')" >> "$GITHUB_OUTPUT"

        # Delete any caches which are here already
        rm -rf ccache*

    - name: Restore ccache
      id: restore-ccache
      uses: actions/cache/restore@v4
      with:
        path: ccache.tar.xz
        key: ccache-${{ steps.cache-keys.outputs.CCKEY }}
        restore-keys: |
          ccache-${{ steps.cache-keys.outputs.YMDH }}
          ccache-${{ steps.cache-keys.outputs.YMD }}
          ccache-${{ steps.cache-keys.outputs.YM }}
          ccache-${{ steps.cache-keys.outputs.Y }}
          ccache-

    - name: Decompress caches
      run: |
        if [[ -f ccache.tar.xz ]]; then tar -xf ccache.tar.xz ; fi

    - name: Print initial cache statistics
      run: |
        ccache -d "$PWD/ccache" -s

    - name: Build SMMTT
      run: |
          # Configure shell and environment
          set -o pipefail
          export PATH="/usr/lib/ccache/bin/:/opt/riscv/bin:$PATH"
          export CCACHE_DIR="$PWD/ccache"

          # Run build and grep for errors
          make -j$(( 2 * $(nproc) )) 2>&1 | tee build.log | \
          { grep -o 'make\(\[[0-9]*\]\)\?: \*\*\* \[.*\] Error [0-9]*' || test $? = 1; }

    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build.log
        path: build.log

    - name: Compress build directory
      run: |
        COMPRESS_FILES="build/rel/qemu/qemu-system-riscv32"
        COMPRESS_FILES="$COMPRESS_FILES build/rel/qemu/qemu-system-riscv64"
        COMPRESS_FILES="$COMPRESS_FILES build/rel/tests32/riscv/sbi.flat"
        COMPRESS_FILES="$COMPRESS_FILES build/rel/tests64/riscv/sbi.flat"
        COMPRESS_FILES="$COMPRESS_FILES build/rel/linux32/arch/riscv/boot/Image"
        COMPRESS_FILES="$COMPRESS_FILES build/rel/linux64/arch/riscv/boot/Image"
        COMPRESS_FILES="$COMPRESS_FILES build/rel/opensbi32/platform/generic/firmware/fw_jump.bin"
        COMPRESS_FILES="$COMPRESS_FILES build/rel/opensbi64/platform/generic/firmware/fw_jump.bin"
        tar -cf - $COMPRESS_FILES | xz -9 -T0 > build.tar.xz

    - name: Upload build directory
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build.tar.xz
        retention-days: 7
        compression-level: 0

    - name: Print final cache statistics
      if: success() || failure()
      run: |
        ccache -d "$PWD/ccache" -s

    - name: Compress cache directories
      if: success() || failure()
      run: |
        # Clear out old bundles
        rm -f ccache.tar.xz

        # Recompress
        find ./ccache -type f -print0 | tar --null -cf - -T - | xz -9 -T0 > ccache.tar.xz

    - name: Save ccache
      uses: actions/cache/save@v4
      if: success() || failure()
      with:
        path: ccache.tar.xz
        key: ${{ steps.restore-ccache.outputs.cache-primary-key }}

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
        isolation: [max, smmtt]
        test: [linux, tests]

    steps:
    - name: Checkout SMMTT
      uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Restore build directory
      uses: actions/download-artifact@v4
      with:
        name: build
        path: .

    - name: Decompress build directory
      run: cat build.tar.xz | xz -d -T0 | tar -xf -

    - name: Run test
      run: |
        make run-${{ matrix.test }}-${{ matrix.isolation }}${{ matrix.bits }} 2>&1 | tee run.log

    - name: Check expected
      if: ${{ matrix.test == 'linux' }}
      run: |
        [[ ! -z $(cat run.log | grep "Unable to mount root fs on unknown-block(0,0)") ]]

    - name: Check expected
      if: ${{ matrix.test == 'tests' }}
      run: |
        [[ ! -z $(cat run.log | grep "EXIT: STATUS=1") ]]
